CREATE DATABASE CRYPTO_DB;
USE DATABASE CRYPTO_DB;
CREATE SCHEMA ANALYTICS;
USE SCHEMA ANALYTICS;
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE TABLE TOKEN_METRICS (
    DATE DATE,
    PRICE_USD FLOAT,
    VOLUME_USD FLOAT,
    MARKET_CAP_USD FLOAT
);
SHOW TABLES;
SELECT * FROM TOKEN_METRICS;
SHOW WAREHOUSES;
USE DATABASE CRYPTO_DB;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS TOKEN_METRICS (
    date DATE,
    token_name STRING,
    price_usd FLOAT,
    volume_usd FLOAT,
    market_cap_usd FLOAT
);

SHOW WAREHOUSES;
SHOW GRANTS TO USER SREETEJA0908;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
  GRANT USAGE ON WAREHOUSE COMPUTE_WH TO USER SREETEJA0908;


